/*
 * This source file was generated by the Gradle 'init' task
 */
package uve;

import java.sql.Date;
import java.time.LocalDate;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import uve.Model.*;
import uve.Model.Vehiculo;
import uve.Model.Coche.Automovil;
import uve.Model.Coche.Camioneta;
import uve.Model.Service.FacturacionService;
import uve.Model.Taller.Reparacion;

public class App {
    
    
       public static void main(String[] args) {
        try {

            // Instanciar taller
            uve.Model.Taller.Taller taller = new uve.Model.Taller.Taller("Taller Central",50);

            // Instanciar vehículos
            Vehiculo camioneta1 = new Camioneta("Toyota", "Hilux", "ABC1233");
            Vehiculo camioneta2 = new Camioneta("Ford", "Ranger", "DEF4546");
            Vehiculo automovil1 = new Automovil("Honda", "Civic", "GHI7859");
            Vehiculo automovil2 = new Automovil("Chevrolet", "Onix", "JKL0122");

            // Asignar reparaciones
            Reparacion rep1 = new Reparacion("Cambio de aceite", 250, "20-10-2020", "Aceite sintético");
            Reparacion rep2 = new Reparacion("Cambio de frenos", 400, "10-01-2019", "Pastillas de freno");
            Reparacion rep3 = new Reparacion("Reparación de motor", 1200, "13-06-2015", "Kit de motor");
            Reparacion rep4 = new Reparacion("Cambio de llantas", 800, "31-04-2015", "Llantas nuevas");
            Reparacion rep5 = new Reparacion("Alineación", 150, "28-02-2024", "Servicio");

            camioneta1.agregarReparacionHistoria(rep1);
            camioneta1.agregarReparacionHistoria(rep2);
            camioneta1.agregarReparacionHistoria(rep5);

            camioneta2.agregarReparacionHistoria(rep3);
            camioneta2.agregarReparacionHistoria(rep4);

            automovil1.agregarReparacionHistoria(rep2);
            automovil1.agregarReparacionHistoria(rep5);

            automovil2.agregarReparacionHistoria(rep1);
            automovil2.agregarReparacionHistoria(rep3);
            automovil2.agregarReparacionHistoria(rep4);

            //Agregar vehículos al taller
            taller.OcuparTaller(camioneta1);
            taller.OcuparTaller(camioneta2);
            taller.OcuparTaller(automovil1);
            taller.OcuparTaller(automovil2);

            //Generar facturación
            FacturacionService.generarFacturaVehiculo(camioneta1); 
            FacturacionService.generarFacturaVehiculo(camioneta2);
            FacturacionService.generarFacturaVehiculo(automovil1);
            FacturacionService.generarFacturaVehiculo(automovil2);

            System.out.println("Facturación generada exitosamente para todos los vehículos.");
        } catch (Exception e) {
            System.out.println("Hubo error XD");
    }

} 
}